-   id: logseq-pre-commit
    name: 'logseq-pre-commit'
    entry: run-logseq-pre-commit.sh
    always_run: true
    language: script
-   id: logseq-post-commit
    name: 'logseq-post-commit'
    entry: run-logseq-post-commit.sh
    always_run: true
    language: script
    stages: [post-commit]
